-- MySQL Script generated by MySQL Workbench
-- Tue Nov 17 10:51:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Jeux
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Jeux
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Jeux` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema Editeur
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Editeur
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Editeur` ;
-- -----------------------------------------------------
-- Schema Joueurs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Joueurs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Joueurs` ;
USE `Jeux` ;

-- -----------------------------------------------------
-- Table `Editeur`.`Editeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Editeur`.`Editeur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Pays` VARCHAR(45) NULL,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jeux`.`Jeux`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jeux`.`Jeux` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Date_de_sortie` VARCHAR(45) NOT NULL,
  `Genre` VARCHAR(45) NOT NULL,
  `Age` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `Créateur`
    FOREIGN KEY ()
    REFERENCES `Editeur`.`Editeur` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Editeur` ;
USE `Joueurs` ;

-- -----------------------------------------------------
-- Table `Joueurs`.`Joueurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Joueurs`.`Joueurs` (
  `id` INT NOT NULL,
  `Age` VARCHAR(45) NOT NULL,
  `Genre` VARCHAR(45) NOT NULL,
  `Préférence` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `Consommateur`
    FOREIGN KEY ()
    REFERENCES `Jeux`.`Jeux` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Consommateur`
    FOREIGN KEY ()
    REFERENCES `Editeur`.`Editeur` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
