-- MySQL Script generated by MySQL Workbench
-- Wed Nov 18 16:10:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Gamingo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Gamingo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Gamingo` DEFAULT CHARACTER SET utf8 ;
USE `Gamingo` ;

-- -----------------------------------------------------
-- Table `Gamingo`.`Editeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gamingo`.`Editeur` (
  `Square_Enix` INT NOT NULL,
  `Total_War` INT NOT NULL,
  `Nintendo` INT NOT NULL,
  PRIMARY KEY (`Square_Enix`, `Total_War`, `Nintendo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gamingo`.`Jeux`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gamingo`.`Jeux` (
  `Kingdom_Hearts` INT NOT NULL,
  `Final_Fantasy` INT NOT NULL,
  `Dragon_Quest` INT NOT NULL,
  `Rome` INT NOT NULL,
  `Samurai` INT NOT NULL,
  `Warhammer` INT NOT NULL,
  PRIMARY KEY (`Final_Fantasy`, `Kingdom_Hearts`, `Dragon_Quest`, `Rome`, `Samurai`, `Warhammer`),
  INDEX `SourceTW_idx` (`Warhammer` ASC, `Samurai` ASC, `Rome` ASC) VISIBLE,
  CONSTRAINT `SourceSQ`
    FOREIGN KEY (`Final_Fantasy` , `Kingdom_Hearts` , `Dragon_Quest`)
    REFERENCES `Gamingo`.`Editeur` (`Square_Enix` , `Square_Enix` , `Square_Enix`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SourceTW`
    FOREIGN KEY (`Warhammer` , `Samurai` , `Rome`)
    REFERENCES `Gamingo`.`Editeur` (`Total_War` , `Total_War` , `Total_War`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
